import { Metadata } from 'next';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import { Package, Zap, RefreshCw, Lock, Layers, ArrowRight, ExternalLink } from 'lucide-react';
import Link from 'next/link';
import { codeToHtml } from 'shiki';

export const metadata: Metadata = {
  title: 'Python SDK - lobstr.io API Documentation',
  description: 'Official Python SDK for the lobstr.io API. Sync and async clients, typed models, auto-pagination, and full API coverage.',
};

const FEATURES = [
  { icon: Zap, title: 'Sync & Async', description: 'Both LobstrClient and AsyncLobstrClient with identical API surfaces.' },
  { icon: Layers, title: 'Typed Models', description: 'Dataclass models for every response — no raw dicts in the public API.' },
  { icon: RefreshCw, title: 'Auto-Pagination', description: 'Lazy PageIterator streams all pages on demand with .iter() method.' },
  { icon: Lock, title: 'Auto Auth', description: 'Token resolved from explicit param, LOBSTR_TOKEN env, or ~/.config/lobstr/config.toml.' },
];

const RESOURCES = [
  { name: 'client.me() / client.balance()', description: 'User profile and credit balance' },
  { name: 'client.crawlers.*', description: 'List, get, params, attributes' },
  { name: 'client.squids.*', description: 'Create, list, get, update, empty, delete' },
  { name: 'client.tasks.*', description: 'Add, list, get, upload (CSV/TSV), delete' },
  { name: 'client.runs.*', description: 'Start, list, get, stats, tasks, abort, download, wait' },
  { name: 'client.results.*', description: 'List with auto-pagination' },
  { name: 'client.accounts.*', description: 'List, get, types, sync, sync_status, update, delete' },
  { name: 'client.delivery.*', description: 'Email, Google Sheet, S3, webhook, SFTP + test methods' },
];

const INSTALL_CODE = 'pip install lobstrio-sdk';

const QUICK_START = `from lobstrio import LobstrClient

client = LobstrClient()  # auto-resolves token

# Get account info
user = client.me()
print(f"{user.email} — {client.balance().credits} credits")

# Create a squid and scrape
squid = client.squids.create(
    crawler="google-maps-leads-scraper",
    name="Restaurants Paris"
)
client.squids.update(squid.id, params={"country": "France", "max_results": 50})
client.tasks.add(squid=squid.id, tasks=[
    {"url": "https://google.com/maps/search/restaurants+paris"}
])

# Start and wait for completion
run = client.runs.start(squid=squid.id)
run = client.runs.wait(run.id)

# Get results
for page in client.results.iter(run=run.id):
    for place in page.data:
        print(f"{place['name']} — {place['score']}★")`;

const ASYNC_EXAMPLE = `import asyncio
from lobstrio import AsyncLobstrClient

async def main():
    async with AsyncLobstrClient() as client:
        squids = await client.squids.list()
        for squid in squids.data:
            print(f"{squid.name} ({squid.id})")

asyncio.run(main())`;

// Safe: html generated by Shiki at build time from hardcoded code strings, not user input
async function CodeBlock({ code, lang }: { code: string; lang: string }) {
  const html = await codeToHtml(code, { lang, theme: 'github-light' });
  return (
    <div
      className="[&>pre]:!bg-[#F6F8FA] [&>pre]:!p-5 [&>pre]:!m-0 [&>pre]:!rounded-b-lg [&>pre]:!text-[13px] [&>pre]:!leading-relaxed [&>pre]:!overflow-x-auto [&_code]:!text-[13px]"
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}

export default async function SdkPage() {
  return (
    <div className="min-h-screen bg-white">
      <Header />

      {/* Hero */}
      <section className="border-b border-[#E5E7EB]">
        <div className="max-w-4xl mx-auto px-6 py-20 text-center">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-[#FEF2F2] text-[#FF0000] text-sm font-semibold mb-6">
            <Package className="w-4 h-4" />
            Python SDK
          </div>
          <h1 className="text-[42px] font-bold text-[#0A2540] leading-tight mb-5">
            lobstrio-sdk
          </h1>
          <p className="text-lg text-[#0A2540]/70 max-w-2xl mx-auto leading-relaxed">
            Official Python SDK for the lobstr.io API. Typed models, sync &amp; async clients, auto-pagination, and full API coverage — one dependency (httpx).
          </p>
          <div className="mt-8 flex items-center justify-center gap-4">
            <a href="#quickstart" className="inline-flex items-center gap-2 px-5 py-2.5 bg-[#FF0000] text-white rounded-lg font-semibold text-sm hover:bg-[#E60000] transition">
              Quick Start <ArrowRight className="w-4 h-4" />
            </a>
            <a href="https://pypi.org/project/lobstrio-sdk/" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 px-5 py-2.5 text-[#FF0000] hover:text-white rounded-lg font-semibold text-sm border border-[#FF0000] hover:bg-[#FF0000] transition">
              PyPI <ExternalLink className="w-3.5 h-3.5" />
            </a>
          </div>
        </div>
      </section>

      {/* Install */}
      <section className="border-b border-[#E5E7EB]">
        <div className="max-w-4xl mx-auto px-6 py-16">
          <h2 className="text-[28px] font-bold text-[#0A2540] mb-6">Installation</h2>
          <div className="border border-[#E5E7EB] rounded-lg overflow-hidden">
            <div className="px-5 py-3 bg-[#F9FAFB] border-b border-[#E5E7EB] text-sm font-semibold text-[#0A2540]">Terminal</div>
            <CodeBlock code={INSTALL_CODE} lang="bash" />
          </div>
          <p className="text-sm text-[#0A2540]/50 mt-3">Requires Python 3.10+. Only dependency: httpx.</p>
        </div>
      </section>

      {/* Features */}
      <section className="border-b border-[#E5E7EB]">
        <div className="max-w-4xl mx-auto px-6 py-16">
          <h2 className="text-[28px] font-bold text-[#0A2540] mb-2">Features</h2>
          <p className="text-[#0A2540]/60 mb-10">Everything you need to integrate lobstr.io into your Python applications.</p>
          <div className="grid md:grid-cols-2 gap-4">
            {FEATURES.map((f) => (
              <div key={f.title} className="border border-[#E5E7EB] rounded-lg p-5 hover:border-[#FF0000]/30 transition group">
                <div className="flex items-start gap-3">
                  <div className="w-9 h-9 rounded-lg bg-[#FEF2F2] flex items-center justify-center shrink-0 group-hover:bg-[#FF0000]/10 transition">
                    <f.icon className="w-4.5 h-4.5 text-[#FF0000]" />
                  </div>
                  <div>
                    <h3 className="font-semibold text-sm text-[#0A2540]">{f.title}</h3>
                    <p className="text-sm text-[#0A2540]/60 mt-1 leading-relaxed">{f.description}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Quick Start */}
      <section id="quickstart" className="border-b border-[#E5E7EB]">
        <div className="max-w-4xl mx-auto px-6 py-16">
          <h2 className="text-[28px] font-bold text-[#0A2540] mb-2">Quick Start</h2>
          <p className="text-[#0A2540]/60 mb-6">Full workflow: create squid, add tasks, run, get results.</p>
          <div className="border border-[#E5E7EB] rounded-lg overflow-hidden">
            <div className="px-5 py-3 bg-[#F9FAFB] border-b border-[#E5E7EB] text-sm font-semibold text-[#0A2540]">Python</div>
            <CodeBlock code={QUICK_START} lang="python" />
          </div>

          <h3 className="text-lg font-bold text-[#0A2540] mt-10 mb-4">Async Client</h3>
          <div className="border border-[#E5E7EB] rounded-lg overflow-hidden">
            <div className="px-5 py-3 bg-[#F9FAFB] border-b border-[#E5E7EB] text-sm font-semibold text-[#0A2540]">Python (async)</div>
            <CodeBlock code={ASYNC_EXAMPLE} lang="python" />
          </div>
        </div>
      </section>

      {/* Resources */}
      <section className="border-b border-[#E5E7EB]">
        <div className="max-w-4xl mx-auto px-6 py-16">
          <h2 className="text-[28px] font-bold text-[#0A2540] mb-2">API Resources</h2>
          <p className="text-[#0A2540]/60 mb-10">Full coverage of every lobstr.io API endpoint.</p>
          <div className="border border-[#E5E7EB] rounded-lg overflow-hidden">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-[#F9FAFB] border-b border-[#E5E7EB]">
                  <th className="text-left px-5 py-3 font-semibold text-[#0A2540]">Resource</th>
                  <th className="text-left px-5 py-3 font-semibold text-[#0A2540]">Methods</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#E5E7EB]">
                {RESOURCES.map((r) => (
                  <tr key={r.name}>
                    <td className="px-5 py-3 font-mono text-[13px] text-[#FF0000]">{r.name}</td>
                    <td className="px-5 py-3 text-[#0A2540]/70">{r.description}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="mt-10 text-center">
            <Link href="/docs/authentication" className="inline-flex items-center gap-2 text-sm font-semibold text-[#FF0000] hover:underline">
              View full API documentation <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
